export default{
	LOGIN: 'LOGIN',
	PLACEHOLDER_USERNAME:'Username or phone',
	PLACEHOLDER_PASSWORD:'Password',
	LOGIN_FB:'Login by Facebook',
	LOGIN_GG:'Login by Google',
	FORGOT_PASSWORD:'Forgot password?',
	NO_ACCOUNT:'You have no account?',
	SIGNUP_NOW:'Sign up now',
	CONFIRM:'CONFIRM',
	START:'START',
	BANK_ACCOUNT:'BANK ACCOUNT',
	BANK_ACCOUNT_NUMBER:'Account number',
	BANK_ACCOUNT_NUMBER_DETAIL:'Account number of bank',
	BANK_ACCOUNT_OWNER:'Owner',
	BANK_ACCOUNT_OWNER_DETAIL:'Name of owner',
	BANK_NAME:'Bank name',
	BANK_NAME_DETAIL:'Name of Bank',
	BANK_BRANCH:'Branch',
	BANK_BRANCH_DETAIL:'Bank branch name',
	PAY_CASH:'PAY CASH',
	PAY_CASH_NOTE:'To pay COD, please provide the following information (only enter once)',
	PAY_CLEARING:'PAY CLEARING',
	PAY_CLEARING_NOTE:'To ensure your legal rights, please provide the following information (only enter once):',
	TEXT_AGREEMENT : 'I have read and agree',
	TEXT_AGREEMENT_DETAIL:'By agreeing, you are committed to comply with the terms of the above contract regarding the use of Speedlink\'s services.',
	USERNAME:'Your name',
	USERNAME_DETAIL:'Your full name',
	EMAIL:'Email',
	EMAIL_DETAIL:'Email',
	PASSWORD:'Password',
	PASSWORD_DETAIL:'Enter your password',
	PASSWORD_CONFIRM:'Confirm password',
	PASSWORD_CONFIRM_DETAIL:'Enter your password again',
	ADDRESS:'ADDRESS',
	ADDRESS_DETAIL:'Home/Street',
	CITY:'City/Province',
	TITLE_PERSONAL_INFO:'PERSONAL INFROMATION',
	TITLE_PAYMENT:'PAYMENTS',
	TITLE_SERVICE_CONTRACT:'SERVICES CONTRACT',
	TITLE_BANK_ACCOUNT:'BANK ACCOUNT',
	TITLE_SERVICE_REGISTER:'Service Register',
	////
	CASH:'CASH',
	CASH_DETAIL:'charge directly in each bill',
	CLEARING:'CLEARING',
	CLEARING_DETAIL:'I dont know how to explain',
	////
	UPLOAD_IMAGE_ID:'UPLOAD IDENTITY IMAGE',
}